### ISSUE TITLE
Fullcount Alpha Milestones

### ISSUE THREAD

**Issue by s-c-orr** [moonstream-to/fullcount.xyz#131]
Features:
- [ ] Full at-bats
- [ ] Mobile support
- [ ] Cycle of bot opponents
    - [ ] Play patterns
    - [ ] Characters
    - [ ] Art
    - [ ] Progression

UI/UX:
- [ ] Styling
- [ ] Logo

Onboarding: 
- [ ] Onboarding flow
- [ ] What wallets to support
- [ ] Account abstraction 
- [ ] Test

Playtest:
- [ ] Web
- [ ] Mobile
- [ ] Variety of wallets
- [ ] Variety of browsers
